//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepemePlease
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public int employee_id { get; set; }
        public string employee_login { get; set; }
        public string employee_password { get; set; }
    }
}
