//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepemePlease
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int order_id { get; set; }
        public int ordered_good { get; set; }
        public int order_count { get; set; }
    
        public virtual goods goods { get; set; }
    }
}
